name: Build Android Release AAB

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'

      - name: Find Project Directory and Build
        run: |
          PROJECT_DIR=$(find . -name "pubspec.yaml" -exec dirname {} \;)
          echo "Found project in: $PROJECT_DIR"
          cd "$PROJECT_DIR"
          flutter pub get
          flutter build appbundle --release --dart-define=CI=true

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-bundle
          path: '**/build/app/outputs/bundle/release/app-release.aab'
